### PR TITLE
Fix typos and grammatical errors in the README

### PR DESCRIPTION
**Pull request by BonfaceKilz**
#### Description

This PR fixes some typos and grammatical errors in the README.

### CODE REVIEW

**Comment by BonfaceKilz** [comment]
Hi @alivx I had a look at this. This may solve a problem we have at work, whereby we'd want to mirror redis items from a given node. I'll explore this further later--- hopefully I can send in a patch with tty set up :)

**Review by alivx — APPROVED** [review]

**Comment by alivx** [comment]
@BonfaceKilz yes 👍🏻

**Comment by alivx** [comment]
@BonfaceKilz I added new changes to this repo, please check it out.

**Comment by BonfaceKilz** [comment]
Ali Baker <notifications@github.com> writes:

> @BonfaceKilz I added new changes to this repo, please check it out.

Thanks for the heads up; I appreciate the work you
are doing so far. I've skimmed through the
changes; and it LGTM. I see you've added an option
to set auth. That's useful. I'll try to squeeze in
some time and hack on this :)

-- 
Bonface M. K. D4F09EB110177E03C28E2FE1F5BBAE1E0392253F
Humble GNU Emacs User / Bearer of scheme-y parens
Curator: <https://upbookclub.com> / Twitter: @BonfaceKilz

**Comment by alivx** [comment]
I added a lot of good improvement, your feedback is highly appreciated @BonfaceKilz :)

**Comment by BonfaceKilz** [comment]
+1

**Pull request merged**
